# Generated by Django 5.0.3 on 2024-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("deadline", models.DateTimeField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
