# Generated by Django 5.0.3 on 2024-04-01 19:56

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(0, "Not Started"), (1, "In Progress"), (2, "Done")], default=0
            ),
            preserve_default=False,
        ),
    ]
