# Generated by Django 5.0.3 on 2024-04-01 20:34

import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_service", "0002_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(0, "Created"), (1, "In Progress"), (2, "Done")]
            ),
        ),
    ]
