# Generated by Django 5.0.3 on 2024-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_service", "0003_task_created_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
