# Generated by Django 5.0.3 on 2024-04-02 12:40

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_service", "0005_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(0, "Created"), (1, "In Progress"), (2, "Done")], default=0
            ),
        ),
    ]
